### PR TITLE
Update to add Play 2.9 support, bump akka and brotli4j dependencies

### PR DESCRIPTION
**Pull request by henricook**
On Play 2.9.0(RC2) the Brotli filter causes a runtime exception:

```
Uncaught error from thread [application-akka.actor.default-dispatcher-8]: 'void play.api.mvc.Result.<init>(play.api.mvc.ResponseHeader, play.api.http.HttpEntity, scala.Option, scala.Option, scala.collection.immutable.Seq)', shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for ActorSystem[application]
java.lang.NoSuchMethodError: 'void play.api.mvc.Result.<init>(play.api.mvc.ResponseHeader, play.api.http.HttpEntity, scala.Option, scala.Option, scala.collection.immutable.Seq)'
	at play.filters.brotli.BrotliFilter.play$filters$brotli$BrotliFilter$$handleResult(BrotliFilter.scala:92)
	at play.filters.brotli.BrotliFilter$$anon$1.$anonfun$apply$1(BrotliFilter.scala:77)
	at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:470)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:63)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:100)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.scala:18)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:94)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:100)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:49)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:48)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

RC2 will be 2.9.0 in about 5 days, no major changes expected.

### CODE REVIEW

**Comment by henricook** [comment]
@mchv Might I beg a review, merge and new version release off you please? We've had to temporarily disable the filter to move ahead with Play 2.9

**Comment by mchv** [comment]
@henricook Oh amazing! Thank you so much for creating this `PR`, this is the first time I hear about this plug-in being used outside of the guardian. I will review this and understand what has changed between 2.8 and 2.9

**Comment by henricook** [comment]
Thanks for making it, we were glad to find it!

**Comment by mchv** [comment]
@henricook I have now updated dependencies in #18 and release `0.11`for play `2.8`.
I have as well release `0.12-RC2` which should work with play `2.9.0-RC2` (see #19)

**Comment by henricook** [comment]
Thanks @mchv !

**Pull request closed without merging**
