### PR TITLE
Add cookie support for the filter in Play 3.0 by copying the result instead of creating a new result (which dropped other fields, like Cookies)

### PR DESCRIPTION
**Pull request by henricook**
https://github.com/guardian/play-brotli-filter/issues/36

I was trying to figure out why `.withCookies` calls on my Results were being dropped and traced it back to the Brotli filter.

Because the filter's creating brand new `Result` objects instead of modifying the one passed to the filter it drops any additional fields (like Cookies).

This preserves the original result, and just alters headers and body to be Brotli'd

@mchv Would love your thoughts on this when you get a chance, we're about to add a hardening cookie to our auth flow from the server side

### CODE REVIEW

**Comment by henricook** [comment]
If we'd like to try and limit any unintended consequences here we could drop this change back to a `.withCookies(newCookies = newCookiesFromOriginalResult)` and keep creating new Result objects

**Comment by mchv** [comment]
Thank you for investigating the issue, and submitting a patch!
I will review this shortly, and hopefully release a new version fixing the problem.

**Comment by mchv** [comment]
Thank you again @henricook for raising this and investigating the issue. You identified the problem correctly and your changes were the right ones! I have just merged #35 from @andrew-nowak who reported the same issue and had same fix than you.

As commented on the other thread:  

- [Initial implementation](https://github.com/guardian/play-brotli-filter/commit/e301182aea5b4da8dbe75201ab51399ca7aaaaf3) had this issue from the beginning as this was inherited from the play Gzip filter implementation at that time.
- [This was fixed](https://github.com/playframework/playframework/pull/6851) about 7 year ago! Sadly I did not noticed it and picked it up at that time.

I have now released a `0.15.2` which fixed this issue.

**Comment by henricook** [comment]
Drats! Should have reviewed the other open MRs first! Thanks for a speedy response

**Pull request closed without merging**
